### ISSUE TITLE
Add helper method for ContentResolver.notifyChange(Uri uri, ContentObserver observer, boolean syncToNetwork)

### ISSUE THREAD

**Issue by Alexander--** [hamsterksu/Android-AnnotatedSQL#15]
It is arguably most important method for people using custom ContentProvider + SyncAdapter with `android:supportsUploading="true"`, yet there is no helper method for it in generated provider.

**Comment by Alexander--** [comment]
Would you accept a pull request with implementation of this feature? It is kind of pain to notify those Uris by hand, so I'd like to add it myself.

**Comment by hamsterksu** [comment]
hi. i haven't got any pull requests

**Comment by Alexander--** [comment]
I will submit one shortly.
