### ISSUE TITLE
Use Proguard

### ISSUE THREAD

**Issue by SilkSama** [hamsterksu/Android-AnnotatedSQL#17]
Hello,
what are the rules to define to use proguard ?
Thx in advance

**Comment by SelvinPL** [comment]
@SilkSama Do you have any problems with proguard? There should be no special rules needed as it is a compile-time code generator.

**Comment by SilkSama** [comment]
Sorry,
it was a mistake from my side.
No problem with the combination between this library and proguard.

Thanks

**Comment by hamsterksu** [comment]
You just need to add rule to keep class name of  generated content provider
